{
  ### Environment Parameters
  debug: false,
  mode: inference,
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 2,
  CUDA_VISIBLE_DEVICES: '1',

  ### Train Parameters
  model_name: '',
    n_classes: 1,
    in_channels: 3,
    base_c: 64,
  inference_mode: 'segmentation',
  task: 'segmentation',
  dataloader: 'Image2Image_zero_pad',
  criterion: 'DiceBCE',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [608, 608],  # DRIVE:608, STARE:704, CHASEDB1:1024

  model_path: 'C:\Users\Murat\PycharmProjects\FSG-Net-pytorch\Pre_Trained_Models\FSG-Net-DRIVE.pt',
  val_x_path: 'C:\Users\Murat\PycharmProjects\FSG-Net-pytorch\Datasets\DRIVE\val\input',
  val_y_path: 'C:\Users\Murat\PycharmProjects\FSG-Net-pytorch\Datasets\DRIVE\val\label',
}
